/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoContentRouteImport } from './routes/video-content'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerformanceMarketingRouteImport } from './routes/performance-marketing'
import { Route as EyegrowRouteImport } from './routes/eyegrow'
import { Route as ExpertiseRouteImport } from './routes/expertise'
import { Route as DigitalInfrastructureRouteImport } from './routes/digital-infrastructure'
import { Route as CrmConversionRouteImport } from './routes/crm-conversion'
import { Route as ContentAuthorityRouteImport } from './routes/content-authority'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'

const VideoContentRoute = VideoContentRouteImport.update({
  id: '/video-content',
  path: '/video-content',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMarketingRoute = PerformanceMarketingRouteImport.update({
  id: '/performance-marketing',
  path: '/performance-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const EyegrowRoute = EyegrowRouteImport.update({
  id: '/eyegrow',
  path: '/eyegrow',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseRoute = ExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalInfrastructureRoute = DigitalInfrastructureRouteImport.update({
  id: '/digital-infrastructure',
  path: '/digital-infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmConversionRoute = CrmConversionRouteImport.update({
  id: '/crm-conversion',
  path: '/crm-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentAuthorityRoute = ContentAuthorityRouteImport.update({
  id: '/content-authority',
  path: '/content-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content-authority': typeof ContentAuthorityRoute
  '/crm-conversion': typeof CrmConversionRoute
  '/digital-infrastructure': typeof DigitalInfrastructureRoute
  '/expertise': typeof ExpertiseRoute
  '/eyegrow': typeof EyegrowRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-content': typeof VideoContentRoute
  '/locations/$city': typeof LocationsCityRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content-authority': typeof ContentAuthorityRoute
  '/crm-conversion': typeof CrmConversionRoute
  '/digital-infrastructure': typeof DigitalInfrastructureRoute
  '/expertise': typeof ExpertiseRoute
  '/eyegrow': typeof EyegrowRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-content': typeof VideoContentRoute
  '/locations/$city': typeof LocationsCityRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content-authority': typeof ContentAuthorityRoute
  '/crm-conversion': typeof CrmConversionRoute
  '/digital-infrastructure': typeof DigitalInfrastructureRoute
  '/expertise': typeof ExpertiseRoute
  '/eyegrow': typeof EyegrowRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-content': typeof VideoContentRoute
  '/locations/$city': typeof LocationsCityRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content-authority'
    | '/crm-conversion'
    | '/digital-infrastructure'
    | '/expertise'
    | '/eyegrow'
    | '/performance-marketing'
    | '/sitemap.xml'
    | '/video-content'
    | '/locations/$city'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content-authority'
    | '/crm-conversion'
    | '/digital-infrastructure'
    | '/expertise'
    | '/eyegrow'
    | '/performance-marketing'
    | '/sitemap.xml'
    | '/video-content'
    | '/locations/$city'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/content-authority'
    | '/crm-conversion'
    | '/digital-infrastructure'
    | '/expertise'
    | '/eyegrow'
    | '/performance-marketing'
    | '/sitemap.xml'
    | '/video-content'
    | '/locations/$city'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentAuthorityRoute: typeof ContentAuthorityRoute
  CrmConversionRoute: typeof CrmConversionRoute
  DigitalInfrastructureRoute: typeof DigitalInfrastructureRoute
  ExpertiseRoute: typeof ExpertiseRoute
  EyegrowRoute: typeof EyegrowRoute
  PerformanceMarketingRoute: typeof PerformanceMarketingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideoContentRoute: typeof VideoContentRoute
  LocationsCityRoute: typeof LocationsCityRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-content': {
      id: '/video-content'
      path: '/video-content'
      fullPath: '/video-content'
      preLoaderRoute: typeof VideoContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-marketing': {
      id: '/performance-marketing'
      path: '/performance-marketing'
      fullPath: '/performance-marketing'
      preLoaderRoute: typeof PerformanceMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eyegrow': {
      id: '/eyegrow'
      path: '/eyegrow'
      fullPath: '/eyegrow'
      preLoaderRoute: typeof EyegrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise': {
      id: '/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-infrastructure': {
      id: '/digital-infrastructure'
      path: '/digital-infrastructure'
      fullPath: '/digital-infrastructure'
      preLoaderRoute: typeof DigitalInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-conversion': {
      id: '/crm-conversion'
      path: '/crm-conversion'
      fullPath: '/crm-conversion'
      preLoaderRoute: typeof CrmConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-authority': {
      id: '/content-authority'
      path: '/content-authority'
      fullPath: '/content-authority'
      preLoaderRoute: typeof ContentAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentAuthorityRoute: ContentAuthorityRoute,
  CrmConversionRoute: CrmConversionRoute,
  DigitalInfrastructureRoute: DigitalInfrastructureRoute,
  ExpertiseRoute: ExpertiseRoute,
  EyegrowRoute: EyegrowRoute,
  PerformanceMarketingRoute: PerformanceMarketingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideoContentRoute: VideoContentRoute,
  LocationsCityRoute: LocationsCityRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
